apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-pyl0
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-pyl0
    app.kubernetes.io/part-of: ci1t-830-0056-app
  name: devfile-sample-pyl0
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-pyl0
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-pyl0
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0056-tenant/ci1t-830-0056-app/devfile-sample-pyl0@sha256:d467a44679d7df4095b1167700796b7025ccfabb98a5e5c8b777c468ec36f6b5
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
